name: Python package

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install special version of nox
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/cs01/nox.git@5ea70723e9e6#egg=nox
    - name: Lint
      run: |
        nox --non-interactive --session lint

  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install special version of nox
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/cs01/nox.git@5ea70723e9e6#egg=nox
    - name: Verify Docs
      run: |
        nox --non-interactive --session docs

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install special version of nox
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/cs01/nox.git@5ea70723e9e6#egg=nox
    - name: Execute Tests
      run: |
        nox --non-interactive --session tests-${{ matrix.python-version }}

  tests-macos:
    runs-on: macos-10.15
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install special version of nox
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/cs01/nox.git@5ea70723e9e6#egg=nox
    - name: Execute Tests
      run: |
        nox --non-interactive --session tests-${{ matrix.python-version }}

  tests-windows:
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install special version of nox
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/cs01/nox.git@5ea70723e9e6#egg=nox
    - name: Execute Tests
      run: |
        nox --non-interactive --session tests-${{ matrix.python-version }}
