# https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

name: Test and possibly Publish

on:
    pull_request:
    push:
    release:
    workflow_dispatch:

jobs:
  lint:
    if: github.event_name == 'pull_request' || github.event_name == 'push' || github.event_name == 'release'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install nox
      run: |
        python -m pip install --upgrade pip
        pip install nox
    - name: Lint
      run: |
        nox --error-on-missing-interpreters --non-interactive --session lint

  docs:
    if: github.event_name == 'pull_request' || github.event_name == 'push' || github.event_name == 'release'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install nox
      run: |
        python -m pip install --upgrade pip
        pip install nox
    - name: Verify Docs
      run: |
        nox --error-on-missing-interpreters --non-interactive --session docs

  tests:
    if: github.event_name == 'pull_request' || github.event_name == 'push' || github.event_name == 'release'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        include:
          - os: windows-latest
            python-version: 3.8
          - os: macos-latest
            python-version: 3.8

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"
    - name: Persistent Github pip cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip${{ matrix.python-version }}
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install nox
      run: pip install nox
    - name: Execute Tests
      run: |
        nox --non-interactive --session tests-${{ matrix.python-version }}

  publish:
    name: Publish to PyPI on release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [docs, lint, tests]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Upgrade pip, Install nox
      run: |
        python -m pip install --upgrade pip
        pip install nox
    - name: Build  sdist and wheel
      run: |
        nox --error-on-missing-interpreters --non-interactive --session build
    - name: Publish to PyPi
      uses: pypa/gh-action-pypi-publish@v1.4.1
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}

  publish-test:
    name: Publish to Test PyPI
    if: github.event_name == 'workflow_dispatch'
    needs: [docs, lint, tests]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Upgrade pip, Install nox
      run: |
        python -m pip install --upgrade pip
        pip install nox
    - name: Build  sdist and wheel
      run: |
        nox --error-on-missing-interpreters --non-interactive --session build
    - name: Publish to PyPi
      uses: pypa/gh-action-pypi-publish@v1.4.1
      with:
        user: __token__
        password: ${{ secrets.test_pypi_password }}
