name: Test all packages (slow)
on:
  workflow_dispatch:

jobs:
  test_all_packages:
    name: Test all packages
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        #os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip, Install nox
      run: |
        python -m pip install --upgrade pip
        python -m pip install nox
    - name: Execute Tests
      run: |
        nox --non-interactive --session test_all_packages-${{ matrix.python-version }}
    - name: Store reports as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: reports-raw
        path: reports
        retention-days: 2

  report_all_packages:
    name: Collate test reports
    needs: test_all_packages
    runs-on: ubuntu-latest

    steps:
    - name: Get report artifacts
      uses: actions/download-artifact@v2
      with:
        name: reports-raw
        path: reports
    - name: Collate reports
      run: |
        ls *
        cat reports/test_install_all_packages_report_* > reports/all_reports.txt
        cat reports/test_install_all_packages_errors_* > reports/all_errors.txt
    - name: Store collated and raw reports as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: reports-final
        path: reports
